### ISSUE TITLE
Missing GSL Dependency on conda-forge

### ISSUE THREAD

**Issue by sstansill** [conda-forge/python-casacore-feedstock#34] opened 2023-10-02 16:00 UTC
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

`conda install conda-forge::python-casacore` has a missing dependence on gsl. Installation is successful but using casacore.tables.table() fails because gsl is missing. If gsl is installed using conda, the package works as expected

### Installed packages

```shell
# Name                    Version                   Build  Channel
anyio                     3.5.0           py311hca03da5_0
appnope                   0.1.2           py311hca03da5_1001
argon2-cffi               21.3.0             pyhd3eb1b0_0
argon2-cffi-bindings      21.2.0          py311h80987f9_0
asttokens                 2.0.5              pyhd3eb1b0_0
async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0          py311hca03da5_0
babel                     2.11.0          py311hca03da5_0
backcall                  0.2.0              pyhd3eb1b0_0
beautifulsoup4            4.12.2          py311hca03da5_0
blas                      1.0                    openblas
bleach                    4.1.0              pyhd3eb1b0_0
brotlipy                  0.7.0           py311h80987f9_1002
bzip2                     1.0.8                h620ffc9_4
c-ares                    1.19.1               h80987f9_0
ca-certificates           2023.08.22           hca03da5_0
casacore                  3.5.0           nompi_py311h8baa3da_111    conda-forge
certifi                   2023.7.22       py311hca03da5_0
cffi                      1.15.1          py311h80987f9_3
cfitsio                   4.3.0                hca87796_0    conda-forge
charset-normalizer        2.0.4              pyhd3eb1b0_0
comm                      0.1.2           py311hca03da5_0
cryptography              41.0.3          py311hd4332d6_0
debugpy                   1.6.7           py311h313beb8_0
decorator                 5.1.1              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
entrypoints               0.4             py311hca03da5_0
executing                 0.8.3              pyhd3eb1b0_0
fftw                      3.3.10          nompi_h3046061_108    conda-forge
gsl                       2.7.1                h442ca57_1
hdf5                      1.14.1          nompi_h3aba7b3_100    conda-forge
icu                       73.1                 h313beb8_0
idna                      3.4             py311hca03da5_0
importlib-metadata        6.0.0           py311hca03da5_0
importlib_metadata        6.0.0                hd3eb1b0_0
importlib_resources       5.2.0              pyhd3eb1b0_1
ipykernel                 6.25.0          py311hb6e6a13_0
ipython                   8.15.0          py311hca03da5_0
jedi                      0.18.1          py311hca03da5_1
jinja2                    3.1.2           py311hca03da5_0
json5                     0.9.6              pyhd3eb1b0_0
jsonschema                4.17.3          py311hca03da5_0
jupyter-lsp               2.2.0              pyhd8ed1ab_0    conda-forge
jupyter_client            8.1.0           py311hca03da5_0
jupyter_core              5.3.0           py311hca03da5_0
jupyter_events            0.6.3           py311hca03da5_0
jupyter_server            2.5.0           py311hca03da5_0
jupyter_server_terminals  0.4.4           py311hca03da5_1
jupyterlab                4.0.6              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         2.22.0          py311hca03da5_0
krb5                      1.20.1               hf3e1bf2_1
libaec                    1.1.1                h13dd4ca_0    conda-forge
libblas                   3.9.0           16_osxarm64_openblas    conda-forge
libboost                  1.82.0               hdbf59fe_1
libboost-python           1.82.0          py311hddbb800_5    conda-forge
libcblas                  3.9.0           16_osxarm64_openblas    conda-forge
libcurl                   8.2.1                h3e2b118_0
libcxx                    16.0.6               h4653b0c_0    conda-forge
libedit                   3.1.20221030         h80987f9_0
libev                     4.33                 h1a28f6b_1
libexpat                  2.5.0                hb7217d7_1    conda-forge
libffi                    3.4.4                hca03da5_0
libgfortran               5.0.0           13_2_0_hd922786_1    conda-forge
libgfortran5              13.2.0               hf226fd6_1    conda-forge
libiconv                  1.16                 h1a28f6b_2
liblapack                 3.9.0           16_osxarm64_openblas    conda-forge
libnghttp2                1.52.0               h62f6fdd_1
libopenblas               0.3.21               h269037a_0
libpng                    1.6.39               h80987f9_0
libsodium                 1.0.18               h1a28f6b_0
libsqlite                 3.43.0               hb31c410_0    conda-forge
libssh2                   1.10.0               h02f6b3c_2
libxcb                    1.15                 hf346824_0    conda-forge
libxml2                   2.10.4               h0dcf63f_1
libxslt                   1.1.37               h80987f9_1
libzlib                   1.2.13               h53f4e23_5    conda-forge
llvm-openmp               14.0.6               hc6e5704_0
lxml                      4.9.3           py311h50ffb84_0
lz4-c                     1.9.4                h313beb8_0
markupsafe                2.1.1           py311h80987f9_0
matplotlib-inline         0.1.6           py311hca03da5_0
mistune                   0.8.4           py311h80987f9_1000
nbclient                  0.5.13          py311hca03da5_0
nbconvert                 6.5.4           py311hca03da5_0
nbformat                  5.9.2           py311hca03da5_0
ncurses                   6.4                  h313beb8_0
nest-asyncio              1.5.6           py311hca03da5_0
notebook-shim             0.2.2           py311hca03da5_0
numpy                     1.26.0          py311he598dae_0
numpy-base                1.26.0          py311hfbfe69c_0
openssl                   3.1.3                h53f4e23_0    conda-forge
packaging                 23.1            py311hca03da5_0
pandocfilters             1.5.0              pyhd3eb1b0_0
parso                     0.8.3              pyhd3eb1b0_0
pexpect                   4.8.0              pyhd3eb1b0_3
pgplot                    5.2.2             h86977c9_1008    conda-forge
pickleshare               0.7.5           pyhd3eb1b0_1003
pip                       23.2.1          py311hca03da5_0
platformdirs              3.10.0          py311hca03da5_0
prometheus_client         0.14.1          py311hca03da5_0
prompt-toolkit            3.0.36          py311hca03da5_0
psutil                    5.9.0           py311h80987f9_0
pthread-stubs             0.3                  h1a28f6b_1
ptyprocess                0.7.0              pyhd3eb1b0_2
pure_eval                 0.2.2              pyhd3eb1b0_0
pycparser                 2.21               pyhd3eb1b0_0
pygments                  2.15.1          py311hca03da5_1
pyopenssl                 23.2.0          py311hca03da5_0
pyrsistent                0.18.0          py311h80987f9_0
pysocks                   1.7.1           py311hca03da5_0
python                    3.11.5          h47c9636_0_cpython    conda-forge
python-casacore           3.5.2           py311h003c353_2    conda-forge
python-dateutil           2.8.2              pyhd3eb1b0_0
python-fastjsonschema     2.16.2          py311hca03da5_0
python-json-logger        2.0.7           py311hca03da5_0
python_abi                3.11                    4_cp311    conda-forge
pytz                      2023.3.post1    py311hca03da5_0
pyyaml                    6.0             py311h80987f9_1
pyzmq                     25.1.0          py311h313beb8_0
readline                  8.2                  h1a28f6b_0
requests                  2.31.0          py311hca03da5_0
rfc3339-validator         0.1.4           py311hca03da5_0
rfc3986-validator         0.1.1           py311hca03da5_0
send2trash                1.8.0              pyhd3eb1b0_1
setuptools                68.0.0          py311hca03da5_0
six                       1.16.0             pyhd3eb1b0_1
sniffio                   1.2.0           py311hca03da5_1
soupsieve                 2.4             py311hca03da5_0
stack_data                0.2.0              pyhd3eb1b0_0
terminado                 0.17.1          py311hca03da5_0
tinycss2                  1.2.1           py311hca03da5_0
tk                        8.6.12               hb8d0fd4_0
tomli                     2.0.1           py311hca03da5_0
tornado                   6.3.2           py311h80987f9_0
traitlets                 5.7.1           py311hca03da5_0
typing-extensions         4.7.1           py311hca03da5_0
typing_extensions         4.7.1           py311hca03da5_0
tzdata                    2023c                h04d1e81_0
urllib3                   1.26.16         py311hca03da5_0
wcslib                    8.1                  hbf8d308_1    conda-forge
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1           py311hca03da5_1
websocket-client          0.58.0          py311hca03da5_4
wheel                     0.41.2          py311hca03da5_0
xorg-kbproto              1.0.7             h27ca646_1002    conda-forge
xorg-libx11               1.8.6                hfd9643e_0    conda-forge
xorg-libxau               1.0.11               hb547adb_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xorg-xextproto            7.3.0             h1a8c8d9_1003    conda-forge
xorg-xproto               7.0.31            h1a28f6b_1007
xz                        5.4.2                h80987f9_0
yaml                      0.2.5                h1a28f6b_0
zeromq                    4.3.4                hc377ac9_0
zipp                      3.11.0          py311hca03da5_0
zlib                      1.2.13               h53f4e23_5    conda-forge
zstd                      1.5.5                hd90d995_0
```

### Environment info

```shell
active environment : casacore_tmp
    active env location : /Users/seanstansill/miniconda3/envs/casacore_tmp
            shell level : 2
       user config file : /Users/seanstansill/.condarc
 populated config files : /Users/seanstansill/.condarc
          conda version : 23.7.4
    conda-build version : not installed
         python version : 3.11.4.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.5.2=0
                          __unix=0=0
       base environment : /Users/seanstansill/miniconda3  (writable)
      conda av data dir : /Users/seanstansill/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/seanstansill/miniconda3/pkgs
                          /Users/seanstansill/.conda/pkgs
       envs directories : /Users/seanstansill/miniconda3/envs
                          /Users/seanstansill/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.7.4 requests/2.29.0 CPython/3.11.4 Darwin/22.6.0 OSX/13.5.2 solver/libmamba conda-libmamba-solver/23.7.0 libmambapy/1.4.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by pkgw** [comment] 2023-10-12 00:53
Hmm. As far as I can tell, the underlying `casacore` library properly depends on `gsl`, so I'm not sure how this would happen.

Can you provide minimal a `conda create ...` specification that reproduces the issue for you, and the list of packages that are installed for that specification? Does it happen if you set up an environment using entirely packages from conda-forge?

**Comment by AntoniaR** [comment] 2024-07-12 14:37
I think that I found this problem too - basically python-casacore installs but I get the error `ImportError: libgsl.so.25: cannot open shared object file: No such file or directory` when I try to import casacore.measures. Here is some code that should reproduce the error:
```
conda create --name Test_env python=3
conda activate Test_env
conda install conda-forge::python-casacore
python
from casacore.measures import measures
```
gives the error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/P_test/lib/python3.9/site-packages/casacore/measures/__init__.py", line 29, in <module>
    from ._measures import measures as _measures
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
```
Whereas if I just use `pip install python-casacore` I do not get this error.

**Comment by pkgw** [comment] 2024-07-16 13:29
Hmmm. Looking at your report and the initial report, now I'm guessing that the common thread is mixing packages from conda-forge and mainline Anaconda. I wouldn't be surprised if the Anaconda version of libgsl has a different shared object version number (the `25`) in the above.

If you do something like the following:

```
conda create --name Test_env -c conda-forge python=3 python-casacore
```

... does the resulting installation work? This command should install everything from the conda-forge channel, which should make everything self-consistent if my hypothesis is correct.

**Comment by AntoniaR** [comment] 2024-07-17 08:56
The installation seems to work. However, when I conda install the other packages I need, there are a lot of conflicts that needed resolving. Things seem to work after that, but maybe it's worth looking into?
The conda packages there were issues with are given in this command:
`conda install astropy colorlog Jinja2 numpy psycopg2 python-dateutil pytz scipy sqlalchemy=1.4 alembic monotonic psutil pytest dask dask[array]`

**Comment by pkgw** [comment] 2024-07-17 12:19
@AntoniaR OK, yes, that's probably also a consequence of mixing and matching packages from commercial Anaconda and conda-forge. In general, that's something that we don't recommend doing, precisely due to these kinds of problems. Our suggested approach to using conda-forge is to configure your environment to always pull everything from conda-forge:

https://conda-forge.org/docs/user/introduction/#how-can-i-install-packages-from-conda-forge

I feel that our docs on this topic could be a bit better but hopefully that can point you in the right direction. It's helpful to if you're comfortable using Conda sub-environments for this kind of stuff since they help a lot with reducing the odds of messing up your entire installation.

I'm going to close this GitHub issue since I think that the proximate problem is now understood and there isn't anything to be done here in this package about it. Antonia, if you have further problems and get stuck trying to work through them, feel free to reach out to me directly.

**Closed** 2024-07-17 12:19 UTC
Labels: bug
